### PR TITLE
testing framework set up for event_type, event

### PR DESCRIPTION
**Pull request by young-k**
have some basic tests, @noobbyte can possibly add more

### CODE REVIEW

**Comment by Jma353** [comment]
@ifilonenko @ChenJesse @kevingreer feel free to review this so @young-k and @noobbyte can get some feedback from people that are not me.

**Comment by Jma353** [comment]
Biggest thing I noticed is that there's no `tearDown` function, erasing the modifications the tests make to the db.  This is something we just started adding to podcast-backend tests.  I think it might make sense to add this for this PR as you are running tests on a progessively changing db currently.

**Comment by young-k** [comment]
added the tearDown functions and verified that the tests still work

**Comment by Jma353** [comment]
@kevingreer @ChenJesse @ifilonenko @DanielNosrati can you check this out and approve / provide feedback accordingly?

**Pull request merged**
